services:
  - type: web
    name: flask-ocr
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      tesseract --version
      pip install -r requirements.txt
    startCommand: python app.py
